version: "3"
services:
  postgres:
    image: mongo
    container_name: reddlite-db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file: .env
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"
volumes:
  db:
